SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
MAP_WIDTH, MAP_HEIGHT = 60, 60
BLOCK_SIZE = 60
INTERACTION_DISTANCE = 1.5

COIN_IMAGE = None
LANGUAGE_IMAGE = None

WORLDS = {}
CLIENT = None
FONT = None
FONT_BOLD = None
MIDDLE_FONT = None
LARGE_FONT = None
SOUNDS = {}
CLOCKS = []
